# Generated by Django 3.0.5 on 2020-04-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoSintomas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.IntegerField(verbose_name='Operador')),
                ('realizadoPor', models.IntegerField(verbose_name='Realizo')),
                ('temperatura', models.IntegerField(blank=True, null=True, verbose_name='Temperatura')),
                ('malestarGeneral', models.BooleanField(null=True, verbose_name='Maslestar General')),
                ('tosSeca', models.BooleanField(null=True, verbose_name='Tos Seca')),
                ('dolorDeGarganta', models.BooleanField(null=True, verbose_name='Dolor De Garganta')),
                ('congestionNasal', models.BooleanField(null=True, verbose_name='Congestion Nasal')),
                ('dificultaRespiratoria', models.BooleanField(null=True, verbose_name='Dificulta Respiratoria')),
                ('firmaRealizadoPor', models.ImageField(upload_to='FirmaFormatos/%y/%m/%d')),
            ],
            options={
                'verbose_name': 'FormatoSintomas',
                'verbose_name_plural': 'FormatosSintomas',
                'ordering': ['id'],
            },
        ),
    ]
