# Generated by Django 3.0.5 on 2020-04-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCondicionesSalud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDiligenciamiento', models.DateField(verbose_name='Fecha Diligenciamiento')),
                ('preguntaUno', models.IntegerField(verbose_name='Presenta Tos')),
                ('preguntaDos', models.IntegerField(verbose_name='Presenta Escalofrio')),
                ('preguntaTres', models.IntegerField(verbose_name='Presenta Dolor de Garganta')),
                ('PreguntaCuatro', models.IntegerField(verbose_name='Presenta Dolor Corporal')),
                ('preguntaCinco', models.IntegerField(verbose_name='Presenta Dolor de Cabeza')),
                ('preguntaSeis', models.IntegerField(verbose_name='Presenta Fiebre Mayor a 37.8')),
                ('preguntaSiete', models.IntegerField(verbose_name='Presenta Perdida del Olfato')),
                ('preguntaOcho', models.IntegerField(verbose_name='Presenta Dificulta para Respirar')),
                ('preguntaNueve', models.IntegerField(verbose_name='Presenta Fatiga')),
                ('preguntaDiez', models.IntegerField(verbose_name='Has acompado a alguien con COVID-19')),
                ('puntajeTotal', models.IntegerField(verbose_name='Total Puntaje')),
                ('temperatura', models.IntegerField(verbose_name='Grado de Temperatura')),
                ('observaciones', models.CharField(max_length=5000, verbose_name='Observaciones SGSST o Encargado Salud')),
                ('usuarioPruebaRealizada', models.IntegerField(verbose_name='Funcionario a Realizar Prueba')),
                ('encargadoObra', models.IntegerField(verbose_name='Encargado Obra')),
                ('inspectorSST', models.IntegerField(verbose_name='Inspector SST')),
            ],
            options={
                'verbose_name': 'ReporteCondicionSalud',
                'verbose_name_plural': 'ReportesCondicionesSalud',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='FormatoSintomas',
        ),
    ]
