# Generated by Django 3.0.5 on 2020-04-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0002_auto_20200425_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=50, verbose_name='Nombre Visitante')),
                ('cedulaTrabajador', models.FloatField(verbose_name='Cedula Visitante')),
                ('eps', models.CharField(max_length=50, verbose_name='EPS')),
                ('afp', models.CharField(max_length=50, verbose_name='AFP')),
                ('arl', models.CharField(max_length=50, verbose_name='ARL')),
                ('nombrePersonaContacto', models.CharField(max_length=50, verbose_name='Nombre Contacto Visitante')),
                ('telefonoPersonaContacto', models.CharField(max_length=50, verbose_name='Telefono Contacto Visitante')),
                ('parentesco', models.CharField(max_length=50, verbose_name='Parentesco Con Visitante')),
                ('dondeVive', models.CharField(max_length=50, verbose_name='Donde Vive')),
            ],
        ),
    ]
