# Generated by Django 3.0.5 on 2020-04-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0003_visitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportecondicionessalud',
            name='firmaEncargadoObra',
            field=models.CharField(blank=True, max_length=1000000, null=True, verbose_name='Firma Encargado Obra'),
        ),
        migrations.AddField(
            model_name='reportecondicionessalud',
            name='firmaInspectorObra',
            field=models.CharField(blank=True, max_length=1000000, null=True, verbose_name='Firma Inspecto Obra'),
        ),
        migrations.AddField(
            model_name='reportecondicionessalud',
            name='firmaUsuarioPrueba',
            field=models.CharField(blank=True, max_length=1000000, null=True, verbose_name='Firma Quien Realizo'),
        ),
    ]
