# Generated by Django 3.0.5 on 2020-04-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0004_auto_20200426_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitante',
            old_name='cedulaTrabajador',
            new_name='cedulaVisitante',
        ),
        migrations.AddField(
            model_name='reportecondicionessalud',
            name='nombreArchivoGenerado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Archivo Generado XLSX'),
        ),
    ]
