# Generated by Django 3.0.5 on 2020-04-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Cargo',
            field=models.CharField(blank=True, help_text='Campo Obligatorio', max_length=200, null=True, unique=True, verbose_name='Cargo Funcionario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.FloatField(blank=True, null=True, verbose_name='Numero Documento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.FloatField(blank=True, null=True, verbose_name='Numero Celular'),
        ),
    ]
