# Generated by Django 3.0.5 on 2020-04-25 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20200424_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Cargo',
            new_name='cargo',
        ),
    ]
